apiVersion: v1
kind: Service
metadata:
  name: mongo-backend
  labels:
    app: mongo-backend
spec:
  type: ClusterIP
  selector:
    app: mongo-backend
  ports:
    - name: mongo
      port: 27017
      targetPort: 27017
