apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo-backend
  labels:
    app: mongo-backend
spec:
  serviceName: mongo-backend
  replicas: 1
  selector:
    matchLabels:
      app: mongo-backend
  template:
    metadata:
      labels:
        app: mongo-backend
    spec:
      containers:
        - name: mongo
          image: mongo:4.4.18
          ports:
            - containerPort: 27017
              name: mongo
          args: ["--bind_ip_all"]
          readinessProbe:
            tcpSocket:
              port: 27017
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            tcpSocket:
              port: 27017
            initialDelaySeconds: 20
            periodSeconds: 10
          volumeMounts:
            - name: mongo-backend-data
              mountPath: /data/db
  volumeClaimTemplates:
    - metadata:
        name: mongo-backend-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
