apiVersion: v1
kind: Service
metadata:
  name: mongo-transactions
  labels:
    app: mongo-transactions
spec:
  type: ClusterIP
  selector:
    app: mongo-transactions
  ports:
    - name: mongo
      port: 27017
      targetPort: 27017
