apiVersion: v1
kind: Service
metadata:
  name: transactions
  labels:
    app: transactions
spec:
  selector:
    app: transactions
  ports:
    - name: http
      port: 3000
      targetPort: http
  type: ClusterIP