apiVersion: apps/v1
kind: Deployment
metadata:
  name: studentportfolio
  labels:
    app: studentportfolio
spec:
  replicas: 2
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: studentportfolio
  template:
    metadata:
      labels:
        app: studentportfolio
    spec:
      # imagePullSecrets:
      #   - name: ghcr-secret
      containers:
        - name: studentportfolio
          image: ghcr.io/feranmi-a/module_6_part3-studentportfolio:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 20
            periodSeconds: 10
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
